"""Builds a job's output files from a finished pipeline result.

Everything the pipeline wrote into its shared WORK_DIR is copied into the
job's own folder here, while the worker still holds the pipeline lock, so a
later analysis cannot overwrite a finished job's files.
"""
import copy
import json
import math
import os
from xml.sax.saxutils import escape

import numpy as np
import rasterio
import rasterio.shutil

GEOTIFF_MEDIA = 'image/tiff; application=geotiff; profile=cloud-optimized'
MEDIA = {
    'contours.geojson': 'application/geo+json',
    'contours.kml': 'application/vnd.google-earth.kml+xml',
    'cost-distance.tif': GEOTIFF_MEDIA,
    'cost-surface.tif': GEOTIFF_MEDIA,
    'attractor-score.tif': GEOTIFF_MEDIA,
    'probability.tif': GEOTIFF_MEDIA,
}
TARR_ONLY = {'probability.tif'}
NODATA = -9999.0


def write_cog(src_path, dst_path):
    """Lossless DEFLATE Cloud-Optimized GeoTIFF with overviews."""
    tmp = dst_path + '.part'
    rasterio.shutil.copy(src_path, tmp, driver='COG', COMPRESS='DEFLATE', PREDICTOR='YES',
                         OVERVIEWS='AUTO', OVERVIEW_RESAMPLING='NEAREST', BIGTIFF='IF_SAFER')
    os.replace(tmp, dst_path)


def write_attractor_score(result, cd_path, dst_path):
    """The web tool's heatmap as data: server._compute_attractor_score_max
    over the Jacobs masks, with the same NoData rule as serve_cost_png."""
    import server  # imported late: server.py is the Flask app module
    with rasterio.open(cd_path) as src:
        cd = src.read(1).astype(np.float64)
        profile = src.profile.copy()
    nodata_mask = (cd <= 0) | (cd == -9999) | np.isinf(cd) | np.isnan(cd)
    jacobs = server._load_jacobs_masks(result, cd.shape)
    score = server._compute_attractor_score_max(jacobs, nodata_mask, cd.shape).astype(np.float32)
    score[nodata_mask] = NODATA
    profile.update(driver='GTiff', dtype='float32', count=1, nodata=NODATA)
    tmp = dst_path + '.src.tif'
    with rasterio.open(tmp, 'w', **profile) as dst:
        dst.write(score, 1)
    write_cog(tmp, dst_path)
    os.remove(tmp)
    return jacobs is not None


def grid_info(cd_path):
    with rasterio.open(cd_path) as src:
        b, t, crs = src.bounds, src.transform, src.crs
        width, height = src.width, src.height
    lat = (b.bottom + b.top) / 2
    dx = abs(t.a) * 111320 * math.cos(math.radians(lat))
    dy = abs(t.e) * 110540
    return {
        'bounds': {'west': b.left, 'south': b.bottom, 'east': b.right, 'north': b.top},
        'crs': crs.to_string() if crs else 'EPSG:4326',
        'cell_size_m': round((dx + dy) / 2, 1),
        'grid': {'width': width, 'height': height},
    }


def enrich_contours(geojson, job_type):
    """Add TAK-friendly callsign/remarks; the pipeline itself is untouched."""
    fc = copy.deepcopy(geojson) if geojson else {'type': 'FeatureCollection', 'features': []}
    for f in fc.get('features', []):
        p = f.setdefault('properties', {})
        if job_type == 'travel_time':
            p['callsign'] = p.get('label') or f"{p.get('hours')}h"
            p['remarks'] = f"Travel time: {_num(p.get('hours'))}h at flat-ground speed"
        else:
            p['callsign'] = f"{p.get('percentile')} Percentile TARR"
            p['remarks'] = f"Threshold: {p.get('threshold_m', 0) / 1000:.2f} km cost-distance"
    return fc


def contours_kml(fc, job_type):
    """KML 2.2 port of app.js downloadContoursKml. Unlike the browser
    version, interior rings (unreachable pockets) are kept."""
    iso = job_type == 'travel_time'
    title = 'Isochrone Contours' if iso else 'TARR Percentile Contours'
    desc = ('Time-based reachability contours generated by WiSAR Decision Support Tool' if iso
            else 'Terrain-Aware Range Rings generated by WiSAR Decision Support Tool')
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<kml xmlns="http://www.opengis.net/kml/2.2">', '<Document>',
           f'<name>{escape(title)}</name>', f'<description>{escape(desc)}</description>']
    for i, f in enumerate(fc.get('features', [])):
        p = f['properties']
        name = f"{p.get('label')} Isochrone" if iso else f"{p.get('percentile')} Percentile TARR"
        style = f'style_{i}'
        rgb = (p.get('color') or '#ffffff').lstrip('#')
        bgr = rgb[4:6] + rgb[2:4] + rgb[0:2]
        out.append(f'<Style id="{style}"><LineStyle><color>ff{bgr}</color><width>2</width></LineStyle>'
                   f'<PolyStyle><color>00{bgr}</color></PolyStyle></Style>')
        geom = f.get('geometry') or {}
        polys = [geom['coordinates']] if geom.get('type') == 'Polygon' else geom.get('coordinates', [])
        for rings in polys:
            if not rings:
                continue
            inner = ''.join(f'<innerBoundaryIs><LinearRing><coordinates>{_coords(r)}</coordinates></LinearRing></innerBoundaryIs>'
                            for r in rings[1:])
            out.append(f'<Placemark><name>{escape(name)}</name><description>{escape(p.get("remarks", ""))}</description>'
                       f'<styleUrl>#{style}</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>'
                       f'{_coords(rings[0])}</coordinates></LinearRing></outerBoundaryIs>{inner}</Polygon></Placemark>')
    out += ['</Document>', '</kml>']
    return '\n'.join(out) + '\n'


def build_outputs(result, job_type, job_dir):
    """Write every output for the job and return (outputs_meta, result_block)."""
    os.makedirs(job_dir, exist_ok=True)
    cd_path = result['cost_distance_path']
    info = grid_info(cd_path)

    fc = enrich_contours(result.get('contour_geojson'), job_type)
    with open(os.path.join(job_dir, 'contours.geojson'), 'w') as fh:
        json.dump(fc, fh)
    with open(os.path.join(job_dir, 'contours.kml'), 'w') as fh:
        fh.write(contours_kml(fc, job_type))

    write_cog(cd_path, os.path.join(job_dir, 'cost-distance.tif'))
    write_cog(result['cost_surface_path'], os.path.join(job_dir, 'cost-surface.tif'))
    warnings = list(result.get('warnings') or [])
    if not write_attractor_score(result, cd_path, os.path.join(job_dir, 'attractor-score.tif')):
        warnings.append({'severity': 'warning', 'source': 'jacobs',
                         'message': 'Terrain-attractor masks were not computed for this run, so the '
                                    'attractor-score raster is all zeros.'})
    if job_type == 'tarr' and result.get('probability_path'):
        write_cog(result['probability_path'], os.path.join(job_dir, 'probability.tif'))

    outputs = {}
    for name, media in MEDIA.items():
        path = os.path.join(job_dir, name)
        if os.path.exists(path):
            outputs[name] = {'media_type': media, 'bytes': os.path.getsize(path)}
    block = dict(info, contour_count=len(fc['features']), warnings=warnings)
    return outputs, block


def _coords(ring):
    return ' '.join(f'{c[0]},{c[1]},0' for c in ring)


def _num(v):
    return int(v) if isinstance(v, float) and v.is_integer() else v
