"""Builds a job's output files from a finished pipeline result.

Everything the pipeline wrote into its shared WORK_DIR is copied into the
job's own folder here, while the worker still holds the pipeline lock, so a
later analysis cannot overwrite a finished job's files.
"""
import copy
import json
import math
import os
from xml.sax.saxutils import escape

import numpy as np
import rasterio
import rasterio.shutil

from . import overlays as ov

GEOTIFF_MEDIA = 'image/tiff; application=geotiff; profile=cloud-optimized'
MEDIA = {
    'contours.geojson': 'application/geo+json',
    'contours.kml': 'application/vnd.google-earth.kml+xml',
    'cost-distance.tif': GEOTIFF_MEDIA,
    'cost-surface.tif': GEOTIFF_MEDIA,
    'attractor-score.tif': GEOTIFF_MEDIA,
    'probability.tif': GEOTIFF_MEDIA,
}
# Colored map overlays (see overlays.py): a PNG preview and an RGBA COG each
for _oid in ov.OVERLAYS:
    MEDIA[ov.png_name(_oid)] = 'image/png'
    MEDIA[ov.tif_name(_oid)] = GEOTIFF_MEDIA
TARR_ONLY = {'probability.tif', ov.png_name('probability'), ov.tif_name('probability')}
NODATA = -9999.0


def write_cog(src_path, dst_path):
    """Lossless DEFLATE Cloud-Optimized GeoTIFF with overviews."""
    tmp = dst_path + '.part'
    rasterio.shutil.copy(src_path, tmp, driver='COG', COMPRESS='DEFLATE', PREDICTOR='YES',
                         OVERVIEWS='AUTO', OVERVIEW_RESAMPLING='NEAREST', BIGTIFF='IF_SAFER')
    os.replace(tmp, dst_path)


def write_attractor_score(result, cd_path, dst_path):
    """The web tool's heatmap as data: server._compute_attractor_score_max
    over the Jacobs masks, with the same NoData rule as serve_cost_png.
    Returns (masks_found, score, nodata_mask) so the colored overlay can be
    drawn from the same numbers."""
    import server  # imported late: server.py is the Flask app module
    with rasterio.open(cd_path) as src:
        cd = src.read(1).astype(np.float64)
        profile = src.profile.copy()
    nodata_mask = (cd <= 0) | (cd == -9999) | np.isinf(cd) | np.isnan(cd)
    jacobs = server._load_jacobs_masks(result, cd.shape)
    score = server._compute_attractor_score_max(jacobs, nodata_mask, cd.shape).astype(np.float32)
    score[nodata_mask] = NODATA
    profile.update(driver='GTiff', dtype='float32', count=1, nodata=NODATA)
    tmp = dst_path + '.src.tif'
    with rasterio.open(tmp, 'w', **profile) as dst:
        dst.write(score, 1)
    write_cog(tmp, dst_path)
    os.remove(tmp)
    return jacobs is not None, score, nodata_mask


def grid_info(cd_path):
    with rasterio.open(cd_path) as src:
        b, t, crs = src.bounds, src.transform, src.crs
        width, height = src.width, src.height
    lat = (b.bottom + b.top) / 2
    dx = abs(t.a) * 111320 * math.cos(math.radians(lat))
    dy = abs(t.e) * 110540
    return {
        'bounds': {'west': b.left, 'south': b.bottom, 'east': b.right, 'north': b.top},
        'crs': crs.to_string() if crs else 'EPSG:4326',
        'cell_size_m': round((dx + dy) / 2, 1),
        'grid': {'width': width, 'height': height},
    }


# CloudTAK styles features from these simplestyle-like properties
# (api/web/src/base/cot.ts) and ignores the pipeline's `color`; without them
# every polygon renders as red #d63939 at 50% fill.
#
# Never set fill opacity to 0: CloudTAK's GeoJSON import (node-cot
# normalize_geojson.js) drops falsy numbers, and from_geojson.js then
# defaults the fill to 50%. Use 0.01 (alpha 2/255 in CoT) for "no fill".
STROKE_WIDTH = 3
FILL_OPACITY = {'tarr': 0.1, 'travel_time': 0.1}


def enrich_contours(geojson, job_type):
    """Add TAK-friendly callsign/remarks and CloudTAK style properties;
    the pipeline itself is untouched."""
    fc = copy.deepcopy(geojson) if geojson else {'type': 'FeatureCollection', 'features': []}
    for f in fc.get('features', []):
        p = f.setdefault('properties', {})
        color = p.get('color') or '#ffffff'
        p.update({'stroke': color, 'stroke-width': STROKE_WIDTH, 'stroke-opacity': 1,
                  'fill': color, 'fill-opacity': FILL_OPACITY[job_type]})
        if job_type == 'travel_time':
            p['callsign'] = p.get('label') or f"{p.get('hours')}h"
            p['remarks'] = f"Travel time: {_num(p.get('hours'))}h at flat-ground speed"
        else:
            p['callsign'] = f"{p.get('percentile')} Percentile TARR"
            p['remarks'] = f"Threshold: {p.get('threshold_m', 0) / 1000:.2f} km cost-distance"
    return fc


def contours_kml(fc, job_type):
    """KML 2.2 port of app.js downloadContoursKml. Unlike the browser
    version, interior rings (unreachable pockets) are kept."""
    iso = job_type == 'travel_time'
    title = 'Isochrone Contours' if iso else 'TARR Percentile Contours'
    desc = ('Time-based reachability contours generated by WiSAR Decision Support Tool' if iso
            else 'Terrain-Aware Range Rings generated by WiSAR Decision Support Tool')
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<kml xmlns="http://www.opengis.net/kml/2.2">', '<Document>',
           f'<name>{escape(title)}</name>', f'<description>{escape(desc)}</description>']
    for i, f in enumerate(fc.get('features', [])):
        p = f['properties']
        name = f"{p.get('label')} Isochrone" if iso else f"{p.get('percentile')} Percentile TARR"
        style = f'style_{i}'
        rgb = (p.get('color') or '#ffffff').lstrip('#')
        bgr = rgb[4:6] + rgb[2:4] + rgb[0:2]
        out.append(f'<Style id="{style}"><LineStyle><color>ff{bgr}</color><width>2</width></LineStyle>'
                   f'<PolyStyle><color>00{bgr}</color></PolyStyle></Style>')
        geom = f.get('geometry') or {}
        polys = [geom['coordinates']] if geom.get('type') == 'Polygon' else geom.get('coordinates', [])
        for rings in polys:
            if not rings:
                continue
            inner = ''.join(f'<innerBoundaryIs><LinearRing><coordinates>{_coords(r)}</coordinates></LinearRing></innerBoundaryIs>'
                            for r in rings[1:])
            out.append(f'<Placemark><name>{escape(name)}</name><description>{escape(p.get("remarks", ""))}</description>'
                       f'<styleUrl>#{style}</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>'
                       f'{_coords(rings[0])}</coordinates></LinearRing></outerBoundaryIs>{inner}</Polygon></Placemark>')
    out += ['</Document>', '</kml>']
    return '\n'.join(out) + '\n'


def build_outputs(result, job_type, job_dir):
    """Write every output for the job and return (outputs_meta, result_block)."""
    os.makedirs(job_dir, exist_ok=True)
    cd_path = result['cost_distance_path']
    info = grid_info(cd_path)

    fc = enrich_contours(result.get('contour_geojson'), job_type)
    with open(os.path.join(job_dir, 'contours.geojson'), 'w') as fh:
        json.dump(fc, fh)
    with open(os.path.join(job_dir, 'contours.kml'), 'w') as fh:
        fh.write(contours_kml(fc, job_type))

    write_cog(cd_path, os.path.join(job_dir, 'cost-distance.tif'))
    write_cog(result['cost_surface_path'], os.path.join(job_dir, 'cost-surface.tif'))
    warnings = list(result.get('warnings') or [])
    masks_found, score, nodata_mask = write_attractor_score(result, cd_path,
                                                            os.path.join(job_dir, 'attractor-score.tif'))
    if not masks_found:
        warnings.append({'severity': 'warning', 'source': 'jacobs',
                         'message': 'Terrain-attractor masks were not computed for this run, so the '
                                    'attractor-score raster is all zeros.'})
    if job_type == 'tarr' and result.get('probability_path'):
        write_cog(result['probability_path'], os.path.join(job_dir, 'probability.tif'))

    overlays = build_overlays(result, job_type, job_dir, cd_path, score, nodata_mask, warnings)

    outputs = {}
    for name, media in MEDIA.items():
        path = os.path.join(job_dir, name)
        if os.path.exists(path):
            outputs[name] = {'media_type': media, 'bytes': os.path.getsize(path)}
    block = dict(info, contour_count=len(fc['features']), warnings=warnings, overlays=overlays)
    return outputs, block


def build_overlays(result, job_type, job_dir, cd_path, score, nodata_mask, warnings):
    """Render the colored map overlays (overlays.py). A layer that can't be
    drawn is skipped with a warning; it never fails the job."""
    renderers = {
        'attractor': lambda: (ov.attractor_rgba(score, nodata_mask), cd_path),
        'terrain': lambda: (ov.terrain_rgba(result['cost_surface_path'], result['dem_path']),
                            result['cost_surface_path']),
        'probability': lambda: (ov.probability_rgba(result['probability_path']), result['probability_path']),
    }
    out = []
    for oid, (title, tarr_only) in ov.OVERLAYS.items():
        if tarr_only and (job_type != 'tarr' or not result.get('probability_path')):
            continue
        if oid == 'terrain' and not (result.get('dem_path') and os.path.exists(result['dem_path'])):
            warnings.append({'severity': 'info', 'source': 'overlay',
                             'message': f'{title} overlay skipped: no elevation data for this run.'})
            continue
        try:
            rgba, ref = renderers[oid]()
            bounds = ov.write_overlay(rgba, ref, os.path.join(job_dir, ov.png_name(oid)),
                                      os.path.join(job_dir, ov.tif_name(oid)), write_cog)
        except Exception as e:  # noqa: BLE001 - an overlay must never fail the job
            for name in (ov.png_name(oid), ov.tif_name(oid)):
                try:
                    os.remove(os.path.join(job_dir, name))
                except OSError:
                    pass
            warnings.append({'severity': 'warning', 'source': 'overlay',
                             'message': f'{title} overlay could not be drawn ({type(e).__name__}: {e}).'})
            continue
        out.append({'id': oid, 'title': title, 'png': ov.png_name(oid), 'geotiff': ov.tif_name(oid),
                    'bounds': bounds})
    return out


def _coords(ring):
    return ' '.join(f'{c[0]},{c[1]},0' for c in ring)


def _num(v):
    return int(v) if isinstance(v, float) and v.is_integer() else v
